baseURL = 'https://www.karsdorp.io'
languageCode = 'en-us'
title = 'Folgert Karsdorp'
theme = "cactus"
copyright = "Folgert Karsdorp; made with Hugo"
refLinksErrorLevel = "WARNING"
publishDir = "docs"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Notebooks"
url = "/posts"
weight = 5

[[menu.main]]
name = "Publications"
url = "/references"
weight=10

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "friendly" # friendly
    tabWidth = 4

[params]

  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  showAllPostsArchive = true # default

  # Home page settings
  
  description = """I'm a researcher in Computational Humanities and Cultural
  Evolution at Amsterdam's [Meertens
  Institute](https://meertens.knaw.nl/index.php/en/), affiliated with the Royal
  Netherlands Academy of Arts and Sciences. I study aspects of cultural change
  and experiment with methods to quantify cultural diversity. A significant
  aspect of my recent work is understanding and accounting for biases in these
  quantifications. I like to use computational models from fields such as
  Machine Learning, Cultural Evolution, and Ecology to aid these investigations.
  Beyond research, I have a passion for teaching computer programming,
  especially within the Humanities context. Together with [Mike
  Kestemont](http://mikekestemont.github.io/) and [Allen
  Riddell](https://www.ariddell.org/), I published the book "Humanities Data
  Analysis" with Princeton University Press, which guides readers on leveraging
  Python for analyzing Humanities data. Check out the open access edition
  [here](https://www.humanitiesdataanalysis.org)!"""
  
  mainSection = "posts" # your main section
  mainSectionTitle = "Notebooks"
  showAllPostsOnHomePage = true # default
  postsOnHomePage = 100 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  showNewsList = false

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  mathjax = true

[markup.goldmark.renderer]
  unsafe = true


[params.comments]
    enabled = false # default

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/fbkarsdorp"
  [[params.social]]
    name = "bluesky"
    link = "https://bsky.app/profile/folgertk.bsky.social"
  [[params.social]]
    name = "email"
    link = "folgert.karsdorp@meertens.knaw.nl"  # no need for "mailto:" in the head
  [[params.social]]
    name = "cv"
    link = "https://raw.githubusercontent.com/fbkarsdorp/fbkarsdorp.github.com/master/tex/main.pdf"
